- patterns.yml
There was a typo in the `sourceName` field for kubernetes hyperkube pattern specification.
Actually, I came here from logagent article on sematext and I'm not really using this project, so feel free to correct me if I have done anything wrong.
> fixed a typo in patterns.yml

- bin/logagent.js
This was preventing the "originalLine" field from showing up
> Fixed originalLine typo

- bin/logagent-setup.sh
As documented in logagent-setup parameters:
`LOGSENE_TOKEN filepattern (/var/log/**/*.log)`
But it didn't work, now it should work.
> Allow specifying the file pattern as $2

- lib/index.js
There are two issues here, one in the call of fs.statSync() and one where the "p" object (metadata) is parsed instead of "parsed" (with the actual data).
> Fix typos that break GeoIP enriching

- lib/plugins/input/command.js
When using the command input, the `sourceName` config item doesn't have any effect because it's used to populate `source` in the context rather than `sourceName`.  This causes the `sourceName` parameter to be `undefined` in the json parser transform function.
> fix undefined sourceName when using command input

- lib/parser/parser.js
- test/test.js
The current [bunyan log version is 0](https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L18) which means that the current test for bunyan log format doesn't work as `parsed.v` won't be truthy.
This patch fixes that issue, adds code to remove the bunyan `time` field after converting it to `@timestamp`, and adds a test for proper bunyan message parsing.
> Bunyan log parsing

- bin/logagent.js
this patch includes:
- fallback for filter name
- rename `initPugins` -> `initPlugins`,
- rename `outputFilterSections` -> `inputFilterSections` for input filters
- switch from `!=` -> `!==`
> assorted odds & ends

- lib/plugins/output/elasticsearch.js
This patch adds support for replacing `YYYY`, `MM` & `DD` in target index names with the full year, month & date respectively.  With this patch a user can specify an index like `logstash-YYYY.MM.DD` to duplicate the behavior of logstash's default index pattern.
This patch also tweaks the preference order for the `Logsene.log` `level` parameter (which is actually used to populate `severity`) to prefer `severity` over `level`.
Finally, it removes an unneeded `if` statement and an unneeded variable `i`.
> Add support for time-based index patterns, prefer severity over level

- lib/parser/maxmind-update.js
- lib/parser/parser.js
Initial maxmind update was failing because of wrong filename, probably introduced by commit 44c7c8eba796ee96e18fdf5687373370ffc73d2e
Also had to move require of maxmind up before trying to stat the file, otherwise it was null when callback was called later.
> Fix initial maxmind update

- bin/logagent.js
Hi,
I've add reference to zeromq input/out plugins. They are external plugins cause library used is based on native. 
Plugins support the following patters
* Publish-subscribe
* Request-response
* fire-and-forget some times called pipeline
Reference plugins 
[input plugin](https://github.com/fbalicchia/logagent-input-zeromq)
[output plugin](https://github.com/fbalicchia/logagent-output-zeromq)
> Zeromq in/out plugins #116

- patterns.yml
Hello, here is my pattern to match Traefik default accesslog.
Traefik have no access log by default, then you will need to use the argument *--accesslog=true*.
> Add a new pattern to match Traefik default accesslog in 'patterns.yml'

- bin/logagent.js
- config/examples/elasticsearch-query-input_prometheus-alertmanager-output.yml
- lib/plugins/output/prometheus-alertmanager.js
- test/output-prometheus-alertmanager-test.js
This adds a output plugin that allows to use query results from elasticsearch, transform and send them as to prometheus alertmanager API.
That way one can re-use existing prometheus alertmanager infrastructure that has lots of alert providers (email, slack, pagerduty, ...).
Note: prometheus alertmanager automatically starts alerts and deduplicates them when sent again. Alerts are closed after defined timeout time (configured in alertmanager).
See https://prometheus.io/docs/alerting/clients/
> Add output prometheus-alertmanager

- bin/logagent.js
This PR ensure that the app properly cleans up after itself (connections closed, file handles terminated, store last file positions) in crash conditions. The use case that led to this PR was noticing that logagentTailPointers.json wasn't being created/updated in case of a plugin throwing an uncaught exception. Obviously, one could ask "why is a plugin throwing an uncaught exception?", but I think that's a much bigger problem.
Added uncaughtException to the set of events that trigger a call to self.terminate()
> self.terminate() on uncaught exceptions

- lib/parser/parser.js
Message level wasn't properly mapped from integer to severity string due to premature type conversion.
> Fix level->severity mapping

- lib/plugins/output/elasticsearch.js
Some of the 'error' events emitted by `logsene-js` contain nested objects. This would cause messages to contain '[Object object]' strings instead of the expected object, which can sometimes be useful to understand the error.
> Convert all values to strings when creating error messages

- bin/logagent.js
- config/example.yml
- dockerhub/run.sh
- lib/core/cliArgs.js
- lib/parser/mergePatternFiles.js
- lib/parser/parser.js
- lib/plugins/input/docker/docker.js
- lib/plugins/input/kubernetesEvents.js
- lib/plugins/output-filter/kubernetes-enrichment.js
- package.json
- patterns.yml
- New command-line argument `--k8sEnrichment` to enable the Kubernetes-Enrichment plugin
- Interpreting Kubernetes annotations 
- `sematext.com/logs-token`, send pod logs to a specific Sematext Logs Token 
- `sematext.com/logs-enabled`, enable/disable pod logs. 
- `sematext.com/logs-remove-fields`, list of fields removed from pod logs 
- Update `container.image.name` with value from `pod.spec.container.image.name`
Bugfix: Docker engine in k8s reports sha256:ID as image name, while the Kubernetes API
provides the correct image name
- Other changes: 
- Update kubernetes-events plugin to latest k8s API client
- Update Redis logs pattern
- Minor bug fixes: 
- Catch `file not found error` when loading pattern files, 
- Parser: Fix issue finding patterns for a source
> Use Kubernetes annotations

- .travis.yml
- bin/logagent.js
- lib/plugins/input/docker/dockerInspect.js
- lib/plugins/output-filter/docker-log-enrichment.js
- lib/plugins/output-filter/kubernetes-enrichment.js
- lib/plugins/output/elasticsearch.js
- lib/util/parser.js
Making log routing more flexible: 
- support multiple elasticsearch urls in `LOGS_RECEIVER_URL` container label/env var 
- support multiple elasticsearch urls in `logs-receiver-url` Kubernetes annotation
- support list of pre-configured ES output plugins by setting `LOGS_DESTINATION=configName,configName2` 
Example 1: 
Run nginx and ship logs to local elasticsearch and to sematext cloud. 
```
docker run -d \
-e LOGS_RECEIVER_URL="https://elasticsearch:9200/logs,https://logsene-receiver.sematext.com/YOUR_TOKEN_HERE" \
-p 8282:80 nginx
```
Logagent will ship logs to both servers. 
Example 2
Assume we have two elasticsearch output plugins configured in loggent.conf:
```
output: 
semtatext:
module: elasticsearch 
url: https://logsene-receiver.sematext.com 
index: YOUR_LOGS_TOKEN
local-elk: …
```
> Make log routing for containers flexible

- bin/logagent.js
- lib/core/logEventEmitter.js
- lib/plugins/input/cassandra.js
- lib/plugins/input/elasticsearchHttp.js
- lib/plugins/input/elasticsearchQuery.js
- lib/plugins/input/influxHttp.js
- lib/plugins/input/journaldUpload.js
- lib/plugins/input/kubernetesAudit.js
- lib/plugins/input/kubernetesEvents.js
- lib/plugins/input/mssql.js
- lib/plugins/input/mysql.js
A new event type `data.object` allows input plugins to emit structured data instead of text lines via `data.raw` events.
- parser and text-based input filters are skipped 
- output-filters are applied before output plugins get ‘data.parsed’ event
- input plugins adjustments using the new event type ‘data.object’. Some input plugins used stringify() and `data.raw` event. We changed the plugins to skip data serialization/deserialization and use directly `data.object` events with a better performance. Input plugins using 'data.parsed' have been changed to use the 'data.object' event, ensuring output filters can be applied.
> Add new pipeline event

- bin/logagent.js
- config/examples/github-webhook-input.yaml
- lib/plugins/input/github.js
- lib/plugins/input/journaldUpload.js
- lib/plugins/input/webhooks/github.js
- lib/plugins/input/webhooks/util.js
- lib/plugins/output/output-http.js
- lib/plugins/output/output-sematext-events.js
- package.json
Added a new input plugin for Github Webhooks. The input plugin will run as a server and listen for HTTP requests. It will take token and region values from the URL and parse an event object from the GitHub Webhook. The output will send an HTTP request to the Sematext Events API.
> SC-7051: Added GitHub Webhook input plugin

- lib/plugins/output-filter/geoip.js
Setting a list of fields to read the IP adress via GEOIP_FIELDS env variable did not work. 
This fix allows to set a list of fields e.g. GEOIP_FIELDS="ClientIP,remote_address,client_ip"
> Fix GEOIP_FIELDS config settings 

- lib/plugins/input/journald-upload.js
- lib/plugins/output-filter/journald-format.js
Systemd-journal-upload works in streaming mode, so we added: 
- streaming mode for HTTP requests
- changed parser  for journald export format to streaming mode
journald-format plugin: 
- improved detection of container logs by `container_name` and not only by `container_full_id`
> Journald streaming mode

- lib/parser/parser.js
- lib/plugins/input/docker/docker.js
- package.json
- patterns.yml
Migrating from date-fns@2.0-alpha6 to date-fns@2.9.0. Including changes for backward compatibility. 
- update existing patterns to new date-fns format strings
-  auto-fix for old dateFormat strings. If such a fix is applied, the parser generates a 1-time warning while loading patterns.  The auto-fix converts `YY -> yy, DD -> dd, Z -> X` and sets 'iso' for ISO date patterns, which must be handled by a separate 'parseISO' function. See: https://github.com/date-fns/date-fns/issues/1643
```
Parser config: You use a deprecated dateFormat in sematext_agent_golang 'YY-MM-ddTHH:mm:ss'' was converted to 'iso' - check your patterns.yml file
Parser config: You use a deprecated dateFormat in sematext_agent_golang 'YY-MM-ddTHH:mm:ss'' was converted to 'iso' - check your patterns.yml file
Parser …
```
> Update date-fns to 2.9.0

- lib/plugins/input/cloudfoundry.js
- lib/plugins/input/heroku.js
- lib/plugins/input/kubernetesAudit.js
Following input plugins use automatic token blacklist: 
- Kubernetes Audit 
- Heroku 
- Cloudfoundry
> Add token blacklists to HTTP receivers

- lib/plugins/output/elasticsearch.js
- lib/util/logger.js
There was a bug in the Elasticsearch output plugin. When setting the `LOGS_TOKEN` in a Docker configuration, while **not** setting the token in the `output` section of the Logagent conf file, the Elasticsearch output plugin would not read the token at all if the logs were being parsed from a file on the host machine.
This adds a fix for setting `LOGS_TOKEN` in a Docker env and reading file input from files on the host machine.
> Issue #206

- lib/plugins/input/webhooks/github.js
- lib/plugins/input/webhooks/util.js
- lib/plugins/output/elasticsearch.js
- lib/plugins/output/output-sematext-events.js
- lib/util/token-blacklist.js
> SC-7164: Added token blacklisting for Github Webhook input

- lib/plugins/input/docker/docker.js
- lib/plugins/input/docker/dockerInspect.js
- lib/plugins/output-filter/kubernetes-enrichment.js
- run.sh
We had a bug in the LOGS_ENABLED and LOGS_ENABLED_DEFAULT logic for whitelisting/blacklisting containers that Logagent should collect logs from.
This fixed #191 the ENV vars logic for Docker, Docker Compose and Docker Stack.
> Fix for #191 - refactoring LOGS_ENABLED logic

- config/example.yml
- config/examples/stdin-gelf-output.yml
- lib/plugins/output/gelfout.js
I noticed that the GELF output plugin fills the screen with a flood of messages.  I found it very helpful to have a debug option for that and only do those if debug=true.  I was thinking others could benefit from this and wanted to submit this PR.  Let me know if there are any concerns or questions.  Thanks.
> Gelf debug option

- lib/plugins/output/gelfout.js
Here is a Pull Request that fixes the leak with graygelf for me.  Let me know if there are any questions or comments or if I can do anything to help.  Thanks!
> Create graygelf in constructor once vs on every call to eventHandler

- bin/logagent.js
- lib/plugins/output-filter/github-logs-format.js
The commits field should be an array to avoid `Too many fields in index` issue.
> Refactor commits field

- lib/plugins/input-filter/kubernetesContainerd.js
- lib/plugins/output-filter/docker-log-enrichment.js
This PR solves the issue of field duplication. 
We have a default `os.host` field and do not need the `container.host.hostname` field at all.
> Removed container.host.hostname from docker and k8s enrichment

- patterns.yml
Added these, plus a few other changes:
- multiple parameters with the same key now go into an array
- we rename fields with no a-zA-z characters (as ES might throw an empty field exception)
- the "richer" regex with hits now goes on top
> params and core parsing to Solr 7.x/8.x logs

- lib/plugins/input/docker/docker.js
- lib/plugins/input/docker/dockerInspect.js
- lib/plugins/output-filter/docker-log-enrichment.js
- lib/plugins/output-filter/kubernetes-enrichment.js
- lib/plugins/output/elasticsearch.js
- lib/util/parser.js
This PR fixes #224 and enables fine-grained log routing with Docker.
I've added another env var option. `LOGS_RECEIVER_URLS` will enable adding multiple receiver URLs in a comma separated list. These URLs need to contain the token/index of the Elasticsearch endpoint as well.
The existing `LOGS_RECEIVER_URL` env var is now limited to one endpoint and requires adding the `LOGS_TOKEN` as a separate env var. 
It is now possible to add `LOGS_TOKEN` and `LOGS_RECEIVER_URL` to the env vars of containers you want to ship logs for. Setting them on a container-basis will overwrite default settings. Using it with `LA_CONFIG_OVERRIDE=true` with `LOGS_ENABLED_DEFAULT=false` in the Logagent container env vars will let you disable log shipping for all containers except for container where you set …
> Fix #224 - Enable advanced log routing when running Logagent with Docker

- patterns.yml
added slowlog parsing and parsing of logs where user@DB is mentioned
I'm attaching a [sample log from Postgres 11](https://github.com/sematext/logagent-js/files/4947253/postgresql-11-main.log)
Though as far as I can tell, Postgres 12 logs seem to be on the same (default) format.
> Extend parsing Postgres logs

- bin/logagent-setup.sh
For systemd users, you'd need a command like:
```
logagent-setup -i TOKEN_GOES_HERE -j
```
The `-j` part signals that we don't want to tail `/var/log`, but rather accept input from `systemd-journal-upload`. Without `-j`, there should be no difference.
With `-j`, we do the following:
- install `systemd-journal-upload` if it doesn't exist (via `apt-get` or `yum`)
- set up `logagent.conf` to listen to `localhost:5731` (a random port) and parse journal data
- set up `journal-upload.conf` to send data to `localhost:5731` using the provided token
- restart both journald-upload and logagent
> logagent-setup makes journald-upload receiver

- config/examples/kubernetes-containerd-log-routing.yml
- lib/plugins/input-filter/kubernetesContainerd.js
> Fixed regex matching for K8s Containerd

- build/ci/Jenkinsfile
Sometimes the Docker bridge network may get stuck. Using host network should make image building more reliable.
> Use --network=host when building images

- bin/logagent.js
- config/examples/output-filter-rename-fields.yml
- lib/plugins/output-filter/rename-fields.js
This PR adds an output filter for renaming fields in log lines.
Eg.
```yaml
outputFilter:
rename-fields:
module: rename-fields
matchSource: !!js/regexp .*
fields:
- fieldName: user
renameTo: user_object
```
This will rename the the `user` field into `user_object`.
Example:
Input
```json
{"user": "{ name: root }", "message": "Client connect: root", "originalLine": "INFO Client connect: root"}
```
Output
```json
{"user_object": "{ name: root }", "message": "Client connect: root", "originalLine": "INFO Client connect: root"}
```
> Output Filter for renaming fields

- lib/plugins/output-filter/github-logs-format.js
- lib/plugins/output/elasticsearch.js
This PR fixes the following errors:
```bash
upstream prematurely closed connection while reading response header from upstream
```
```bash
recv() failed (104: Connection reset by peer) while reading response header from upstream
```
I think this was caused by the `EventEmitter` sending and closing events asynchronously which in turn caused some requests to be closed prematurely.
> SC-9192: Fixing "closed prematurely" Elasticsearch error response

- lib/plugins/input/journald-upload.js
I assume this is a bug where all fields are lowercased, except the "multiline" ones. This is hard to be consistent with the JSON output of `journalctl`, where some newlines are stripped (e.g. `SELINUX_CONTEXT`). We should simply lowercase everything.
> Lowercase multiline journal fields as well

- lib/plugins/output-filter/kubernetes-enrichment.js
The K8s enrichment filter had a bug and dropped the first couple of initial logs when is just started. This PR fixes this and now the logs are not dropped.
> Hotfix: Fix for K8s enrichment dropping logs

- patterns.yml
Applies to something like:
```
2020-09-19 16:48:35.931 [warning] <0.1429.0> closing AMQP connection <0.1429.0> (127.0.0.1:54326 -> 127.0.0.1:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection
```
Where the `message` would begin with `:` and it would look ugly.
> made colon optional for authentication messages

- bin/logagent-setup.sh
I'm trying to make it easier to add new sources (and new app destinations), once this "system" config is in place.
This commit will only remove fields if we match the `journald` source, and the same with the output. Ideally, we'd do the same for the `journald-format` filter, but I don't know how to do that (besides patching the filter itself). It seems to work for now, so I'll leave it as is.
> Make default journald config easier to extend

- bin/logagent-setup.sh
Added a `-c` option which allows you to provide a random config file, which we install in `/etc/sematext/logagent-conf` and create the service. No token needed.
The bad news is, we don't ask for token anymore if `logagent-setup` is ran badly (e.g. with no arguments). We just provide the help and exit. IMO, this is what we should have been doing anyway :)
> logagent-setup: install service with custom config

- config/examples/output-files.yml
- lib/plugins/output/files.js
I've found some code I think was executed after the `stream.write()` method is called, which causes this issue. This is now fixed.
Fixes #256.
> Fix #256 Write after stream end

- bin/logagent.js
- config/examples/heroku-elasticsearch.yml
- config/examples/heroku-stdout-yml.yml
- lib/plugins/input/heroku.js
- lib/plugins/output-filter/cloudfoundry-format.js
- lib/plugins/output-filter/heroku-format.js
This PR adds destructuring of structured JSON log messages in Heroku.
> Added Heroku log formatting for JSON log messages

- bin/logagent.js
- config/examples/aws-ecs-input-es-output.yml
- lib/plugins/input/aws-ecs.js
- lib/plugins/output-filter/aws-ecs-format.js
> Add aws-ecs input and output filter

- lib/plugins/output/elasticsearch.js
Thanks to @comel, this PR fixes #180 Elasticsearch indice with date error
> fix error using date based index on elasticsearch

- bin/logagent-setup.sh
- bin/logagent.js
- config/example.yml
- config/examples/command-input-journald-output-es.yml
- config/examples/journald-and-file-input-output-es-multiple-indices.yml
- config/examples/journald-upload-receiver.yaml
- lib/plugins/output-filter/journald-format.js
This PR adds a `matchSource` config option to make sure you can match only `journald` logs to the journald-format outputFilter. Eg:
```yaml
outputFilter:
journald-format:
module: journald-format
parseMessageField: true
matchSource: !!js/regexp journald
```
> Added matchSource for `journald-format`

- config/examples/vercel-input-es-output.yml
- lib/plugins/input/vercel.js
- test/vercel/vercelSignature.spec.js
> Refactoring to use multiple Vercel client secrets

- lib/plugins/input/journald-upload.js
After some old refactoring in `64f435872178ea16357e4bcad13b3a3db63f6802` the function `parseLine` became unused and still in the code, moreover `removeFields` parameter from configuration was not working. This PR returns usage of `removeFields` as it was before the refactoring.
Also fixed a bug with include/exclude parameter (hint: `log._SYSTEMD_UNIT !== log[_SYSTEMD_UNIT]`).
And also ignore messages in journald not coming from systemd services (I had audit and kernel syslog messages flooding my logs). This is a questionable change applied only to my setup, so please review it.
> input-journald-upload: use removeFields from config, fix include/exclude test

- lib/plugins/output/aws-elasticsearch.js
update aws elasticsearch output plugin to load credentials from IAM role attached to an EC2 instance.
The PR belongs to this issue #286
> [load-creds-from-ec2-role]

- .jshintrc
- lib/plugins/output-filter/vercel-format.js
I added a regex to parse the kind of logs the user is asking about. 
They are logs in the syslog format, vercel also provides an option to log in json format, which probably would be parsed correctly.
The regex assumes the same format the user reported, if the log doesn't match that format, it won't be parsed and it will default to the behavior we had until now
> SC-16333 Extract fields from vercel syslog messages
