- .eslintrc.json
- lib/core/cliArgs.js
- lib/core/configLoader.js
- lib/core/logSourceToIndexMapper.js
- lib/parser/maxmind-update.js
- lib/parser/mergePatternFiles.js
- lib/parser/multiLine.js
- lib/parser/parser.js
- lib/parser/timerEvent.js
- lib/plugins/input/files.js
- lib/util/logger.js
- test/http-receiver/httpserver.js
- test/test.js
This isn't complete yet, but I wanted to get your feedback @megastef before going any further with it.
With my own projects I've found it very helpful to use eslint as a sanity check for typos, unused/undefined variables, etc as well as keeping more consistent coding standards.
As I've been writing PRs here it bugged me that I couldn't lint my changes, so I developed a base eslint config by looking at the existing codebase, and took a stab at cleaning up some of the inconsistencies and bugs that running it identified.
There are still a number of issues that I'm not sure how you'd like to resolve, which are:
```
./bin/logagent.js
216:75  error  'context' is defined but never used            no-unused-vars
279:26  error  'e' is defined but never used                  no-unused-vars
284:18 …
```
> [WIP] add eslintrc config, fix various issues identified by eslint

- bin/logagent-setup.sh
Create init.d script to support debian wheezy, needed to silence errors from systemctl and initd checks as they were returning a lot of errors.
> Re Issue #64 Logagent-setup fails to create init.d script

- patterns.yml
Ref: https://github.com/sematext/logagent-js/issues/67
> fix datetime not matching on nginx

- bin/logagent.js
Reset previous commit and add grok alias
> Add alias for grok filter

- lib/plugins/output/elasticsearch.js
- lib/util/config-reducer.js
- lib/util/config-serializer.js
> elasticsearch output plugin: function as config value #135

- bin/logagent.js
- config/example.yml
- config/examples/journald-upload-receiver.yaml
- lib/plugins/input/journald-upload.js
- lib/plugins/input/journaldUpload.js
- lib/plugins/output-filter/journald-format.js
- lib/plugins/output/elasticsearch.js
- lib/util/tokenBlacklist.js
- parsing tokens from url, even when systemd-journal-upload add port and upload in the path 
- blacklist tokens for 5 minutes when indexing in sematext cloud fails
> add error handling for invalid tokens

- package.json
Added `release-it` and `auto-changelog` to devDependencies.
> Edited release-it

- lib/plugins/input/docker/docker.js
- lib/plugins/input/docker/dockerInspect.js
- lib/plugins/output-filter/kubernetes-enrichment.js
- avoid that logs are filtered on docker level too early 
- detach from containers after reading pod annotations 
- refactoring
> fix whitelisting pods via k8s annotations 

- patterns.yml
> Added patterns for Solr 7/8 and audit logs

- build/ci/Jenkinsfile
- build/docker/Dockerfile.amd64
- build/docker/Dockerfile.arm64
Automated builds should push multi-arch manifests and images to DockerHub.
> Add support for building multi-arch images

- config/examples/vercel-input-es-output.yml
- lib/plugins/input/vercel.js
- lib/plugins/output-filter/vercel-format.js
> Vercel integration updates

- bin/logagent.js
- config/examples/cloudfoundry-elasticsearch.yml
- lib/plugins/input/cloudfoundry.js
- lib/plugins/output-filter/cloudfoundry-format.js
- patterns.yml
This PR fixes the log parsing for CloudFoundry logs.
> Fix for CloudFoundry log parsing

- patterns.yml
While at it, I fixed the date parsing for Postgres.
> Expanded RabbitMQ patterns

- lib/plugins/output/elasticsearch.js
- package.json
This PR updates the `logsene-js` logger and adds better error handling.
> Updated `logsene-js` logger

- bin/logagent-setup.sh
There's a new option to `logagent-setup.sh`: `-l` (from Linux). It's used to configure Logagent to pull entries from the Journal via `journalctl`. It's a simpler, arguably better version of `-j`.
I think `-j` still has its use (e.g. if you don't want to run Logagent as root, or one just prefers a "push" model). I think time will tell if we should remove one of them.
> logagent-setup can configure journalctl

- bin/logagent.js
- config/examples/file-input-geoip-es-output.yml
- lib/core/cliArgs.js
- lib/core/configLoader.js
- lib/plugins/output-filter/geoip.js
- package.json
This PR fixes the Geo plugin which was previously broken. Now it will use the Geo enrichment in Sematext  Logs, instead of enriching in Logagent. Docs PR: https://github.com/sematext/docs/pull/252
> SC-8544: Refactor Geo Plugin

- bin/logagent-setup.sh
- bin/logagent.js
- config/examples/command-input-journald-output-es.yml
- config/examples/output-filter-lowercase-fields.yml
- lib/plugins/output-filter/journald-format.js
- lib/plugins/output-filter/lowercase-fields.js
- patterns.yml
> SC-9544: Journald bugfix + Added lowercase filter

- patterns.yml
Simplify and fix. To be honest, I'm not sure how/if it worked so far. I didn't see anything in the `collections` field. My bad :(
> Fix collections pattern for Solr audit logs

- config/examples/aws-ecs-input-es-output.yml
- config/examples/file-input-json-parse-es-output.yml
- lib/plugins/input/aws-ecs.js
- lib/plugins/output-filter/aws-ecs-format.js
Added:
Sample FireLens config:
```json
"logConfiguration": {
"logDriver": "awsfirelens",
"secretOptions": null,
"options": {
"Format": "json",
"Header": "sourceName <nginx/apache/postgres/whatever>",
"compress": "gzip",
"Port": "443",
"Host": "logsene-receiver.apps.sematext.com",
"TLS": "on",
"URI": "/<token>",
"Match": "*",
"Name": "http"
}
},
```
> Improvements to the ECS plugins

- config/examples/syslog-input-es-output.yml
- lib/plugins/input/syslog.js
This PR adds custom tags to Syslog input plugin.
> Add custom tags to Syslog input plugin

- lib/plugins/output-filter/vercel-format.js
This PR solves the issue of dropping cached request logs for Vercel.
> SC-10763: Added formatting for cached requests

- patterns.yml
fixed some patterns and added a new one for login refused
> updated rabbitmq patterns

- lib/plugins/output/aws-elasticsearch.js
revert the changes pushed for loading creds for the role attached to an aws ec2 instance.
> [load-creds-from-ec2-role] 

- lib/plugins/output-filter/kubernetes-enrichment.js
Reverts sematext/logagent-js#295
> Revert "SC-12473 Comment code of container image digest (sha256)"

- lib/plugins/output-filter/dropEventsFilter.js
Fix for debug flag ignore issue:
#305
> Fix for debug flag ignore issue

- package-lock.json
- package.json
It's a dev dependency that's more trouble than it's worth at this point
> Drop prettier-standard
